# permissions to do viewer contents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: content-viewer-role
rules:
- apiGroups:
  - filter.tribit.io
  resources:
  - contents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - filter.tribit.io
  resources:
  - contents/status
  verbs:
  - get
